/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Diego EC Roman
 */
public class MenuTipoRegistro extends javax.swing.JFrame {

    /**
     * Creates new form MenuTipoRegistro
     */
    int xMouse, yMouse;
    public MenuTipoRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        String backtext = "<html><u>Volver a inicio</u></html>";
        btmVolver.setText(backtext);
        SetImageLabel(imglogo, "src/imagenes/logo-120p.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelbckest = new javax.swing.JPanel();
        btmclose = new javax.swing.JLabel();
        btmext = new javax.swing.JLabel();
        panelbck = new javax.swing.JPanel();
        imglogo = new javax.swing.JLabel();
        lblmarca = new javax.swing.JLabel();
        btmVolver = new javax.swing.JLabel();
        PanelBckUser = new javax.swing.JPanel();
        btmUser = new javax.swing.JLabel();
        PanelBckComer = new javax.swing.JPanel();
        btmComer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbckest.setBackground(new java.awt.Color(255, 255, 255));
        panelbckest.setForeground(new java.awt.Color(255, 255, 255));
        panelbckest.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelbckestMouseDragged(evt);
            }
        });
        panelbckest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelbckestMousePressed(evt);
            }
        });

        btmclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N
        btmclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmcloseMouseClicked(evt);
            }
        });

        btmext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-40.png"))); // NOI18N
        btmext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelbckestLayout = new javax.swing.GroupLayout(panelbckest);
        panelbckest.setLayout(panelbckestLayout);
        panelbckestLayout.setHorizontalGroup(
            panelbckestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbckestLayout.createSequentialGroup()
                .addGap(0, 324, Short.MAX_VALUE)
                .addComponent(btmext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmclose))
        );
        panelbckestLayout.setVerticalGroup(
            panelbckestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbckestLayout.createSequentialGroup()
                .addGroup(panelbckestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmclose)
                    .addComponent(btmext))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelbckest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        panelbck.setBackground(new java.awt.Color(255, 255, 255));
        panelbck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N
        panelbck.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 55, 120, 120));

        lblmarca.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblmarca.setForeground(new java.awt.Color(153, 153, 153));
        lblmarca.setText("By TuGuiaAppTeam");
        panelbck.add(lblmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 536, -1, -1));

        btmVolver.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btmVolver.setForeground(new java.awt.Color(0, 153, 255));
        btmVolver.setText("Volver a inicio");
        btmVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmVolverMouseExited(evt);
            }
        });
        panelbck.add(btmVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 450, -1, -1));

        PanelBckUser.setBackground(new java.awt.Color(255, 255, 255));
        PanelBckUser.setForeground(new java.awt.Color(255, 255, 255));

        btmUser.setBackground(new java.awt.Color(255, 255, 255));
        btmUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btmUser.setForeground(new java.awt.Color(21, 171, 146));
        btmUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmUser.setText("USUARIO");
        btmUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        btmUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckUserLayout = new javax.swing.GroupLayout(PanelBckUser);
        PanelBckUser.setLayout(PanelBckUserLayout);
        PanelBckUserLayout.setHorizontalGroup(
            PanelBckUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmUser, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        PanelBckUserLayout.setVerticalGroup(
            PanelBckUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmUser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelbck.add(PanelBckUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 288, -1, -1));

        PanelBckComer.setBackground(new java.awt.Color(255, 255, 255));

        btmComer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btmComer.setForeground(new java.awt.Color(21, 171, 146));
        btmComer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmComer.setText("COMERCIANTE");
        btmComer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        btmComer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmComer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmComerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmComerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckComerLayout = new javax.swing.GroupLayout(PanelBckComer);
        PanelBckComer.setLayout(PanelBckComerLayout);
        PanelBckComerLayout.setHorizontalGroup(
            PanelBckComerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmComer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBckComerLayout.setVerticalGroup(
            PanelBckComerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmComer, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelbck.add(PanelBckComer, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 382, 197, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenid@ al registro de TuGuiaApp");
        panelbck.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 209, 261, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Por favor seleccionar el tipo de usuario que seras.");
        panelbck.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 235, -1, -1));

        jPanel1.add(panelbck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btmcloseMouseClicked

    private void btmextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmextMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btmextMouseClicked

    private void panelbckestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbckestMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelbckestMousePressed

    private void panelbckestMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbckestMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelbckestMouseDragged

    private void btmUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmUserMouseEntered
        // TODO add your handling code here:
        PanelBckUser.setBackground(new Color(21, 171, 146));
        btmUser.setForeground(Color.white);
    }//GEN-LAST:event_btmUserMouseEntered

    private void btmUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmUserMouseExited
        // TODO add your handling code here:
        PanelBckUser.setBackground(Color.WHITE);
        btmUser.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_btmUserMouseExited

    private void btmComerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmComerMouseEntered
        // TODO add your handling code here:
        PanelBckComer.setBackground(new Color(21, 171, 146));
        btmComer.setForeground(Color.white);
    }//GEN-LAST:event_btmComerMouseEntered

    private void btmComerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmComerMouseExited
        // TODO add your handling code here:
        PanelBckComer.setBackground(Color.WHITE);
        btmComer.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_btmComerMouseExited

    private void btmVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmVolverMouseClicked
        // TODO add your handling code here:
        MenuInicio MI = new MenuInicio();
        MI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmVolverMouseClicked

    private void btmUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmUserMouseClicked
        // TODO add your handling code here:
        RegistroUser RU = new RegistroUser();
        RU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmUserMouseClicked

    private void btmVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmVolverMouseEntered
        // TODO add your handling code here:
        btmVolver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btmVolverMouseEntered

    private void btmVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmVolverMouseExited
        // TODO add your handling code here:
        btmVolver.setForeground(new Color(0,153,255));
    }//GEN-LAST:event_btmVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTipoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTipoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTipoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTipoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTipoRegistro().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBckComer;
    private javax.swing.JPanel PanelBckUser;
    private javax.swing.JLabel btmComer;
    private javax.swing.JLabel btmUser;
    private javax.swing.JLabel btmVolver;
    private javax.swing.JLabel btmclose;
    private javax.swing.JLabel btmext;
    private javax.swing.JLabel imglogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JPanel panelbck;
    private javax.swing.JPanel panelbckest;
    // End of variables declaration//GEN-END:variables
}
