/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Combu
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int xMouse, yMouse;
    
    Conexion cx;
    public MenuInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        SetImageLabel(lblMinicio,"src/imagenes/logo.png");
        cx = new Conexion("usuarios");
        cx.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBckBase = new javax.swing.JPanel();
        PanelBckbtmcerrar = new javax.swing.JPanel();
        btmclose = new javax.swing.JLabel();
        btmext = new javax.swing.JLabel();
        PanelBckder = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblimgUser = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblMinicio = new javax.swing.JLabel();
        btmestcx = new javax.swing.JLabel();
        PanelBckbtmLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        PanelBckbtmRegistrar = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        PanelBckBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBckBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBckbtmcerrar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBckbtmcerrar.setForeground(new java.awt.Color(255, 255, 255));
        PanelBckbtmcerrar.setOpaque(false);
        PanelBckbtmcerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelBckbtmcerrarMouseDragged(evt);
            }
        });
        PanelBckbtmcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBckbtmcerrarMousePressed(evt);
            }
        });

        btmclose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btmclose.setForeground(new java.awt.Color(21, 171, 146));
        btmclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N
        btmclose.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btmclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmcloseMouseClicked(evt);
            }
        });

        btmext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-40.png"))); // NOI18N
        btmext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBckbtmcerrarLayout = new javax.swing.GroupLayout(PanelBckbtmcerrar);
        PanelBckbtmcerrar.setLayout(PanelBckbtmcerrarLayout);
        PanelBckbtmcerrarLayout.setHorizontalGroup(
            PanelBckbtmcerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckbtmcerrarLayout.createSequentialGroup()
                .addGap(0, 324, Short.MAX_VALUE)
                .addComponent(btmext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmclose))
        );
        PanelBckbtmcerrarLayout.setVerticalGroup(
            PanelBckbtmcerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btmext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelBckBase.add(PanelBckbtmcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        PanelBckder.setBackground(new java.awt.Color(255, 255, 255));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setForeground(new java.awt.Color(190, 193, 198));
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(190, 193, 198));
        txtPassword.setText("******");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });

        lblimgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-24.png"))); // NOI18N

        lblpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-desbloquear-24.png"))); // NOI18N

        lblMinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N

        btmestcx.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        btmestcx.setForeground(new java.awt.Color(153, 153, 153));
        btmestcx.setText("V. 1.0");
        btmestcx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmestcx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmestcxMouseClicked(evt);
            }
        });

        PanelBckbtmLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(21, 171, 146));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("LOGIN");
        lblLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckbtmLoginLayout = new javax.swing.GroupLayout(PanelBckbtmLogin);
        PanelBckbtmLogin.setLayout(PanelBckbtmLoginLayout);
        PanelBckbtmLoginLayout.setHorizontalGroup(
            PanelBckbtmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        PanelBckbtmLoginLayout.setVerticalGroup(
            PanelBckbtmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        PanelBckbtmRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(21, 171, 146));
        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistro.setText("REGISTRAR");
        lblRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        lblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckbtmRegistrarLayout = new javax.swing.GroupLayout(PanelBckbtmRegistrar);
        PanelBckbtmRegistrar.setLayout(PanelBckbtmRegistrarLayout);
        PanelBckbtmRegistrarLayout.setHorizontalGroup(
            PanelBckbtmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PanelBckbtmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        PanelBckbtmRegistrarLayout.setVerticalGroup(
            PanelBckbtmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(PanelBckbtmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBckderLayout = new javax.swing.GroupLayout(PanelBckder);
        PanelBckder.setLayout(PanelBckderLayout);
        PanelBckderLayout.setHorizontalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckderLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckderLayout.createSequentialGroup()
                        .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBckderLayout.createSequentialGroup()
                                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpass, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblimgUser, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(7, 7, 7)
                                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelBckderLayout.createSequentialGroup()
                                .addComponent(PanelBckbtmLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PanelBckbtmRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))
                    .addComponent(btmestcx, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckderLayout.createSequentialGroup()
                        .addComponent(lblMinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        PanelBckderLayout.setVerticalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckderLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblMinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimgUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpass)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBckbtmLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelBckbtmRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btmestcx))
        );

        PanelBckBase.add(PanelBckder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBckBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBckBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btmcloseMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
                try {
            String user = txtUsuario.getText();
            String password = String.valueOf(txtPassword.getPassword());
            String query = "SELECT * FROM usuarios WHERE user='" + user + "' and password='" + password + "'";
            Statement st = cx.Conectar().createStatement();
            ResultSet rs = st.executeQuery(query);
            if (user.equals("") || password.equals("") || user.equals("Usuario") || password.equals("******")) {
                JOptionPane.showMessageDialog(this, "Alguno de los campos esta en blanco");
            } else {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Bienvenid@ " + txtUsuario.getText() + " !!");
                    MenuPrincipal mnp =new MenuPrincipal();
                    this.setVisible(false);
                    mnp.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario no existe en la base de datos");
                    txtUsuario.setText("Usuario");
                    txtUsuario.setForeground(new Color(190, 193, 198));
                    txtPassword.setText("******");
                    txtPassword.setForeground(new Color(190, 193, 198));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLoginMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained

    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained

    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("Usuario")){
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.black);
        }
        //[190,193,198]
        if(String.valueOf(txtPassword.getPassword()).isEmpty()){
        txtPassword.setText("******");
        txtPassword.setForeground(new Color(190,193,198));
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        if(String.valueOf(txtPassword.getPassword()).equals("******")){
        txtPassword.setText("");
        txtPassword.setForeground(Color.BLACK);
        }
        if(txtUsuario.getText().isEmpty()){
        txtUsuario.setText("Usuario");
        txtUsuario.setForeground(new Color(190, 193, 198));
        }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        RegistroUser RGU = new RegistroUser();
        //this.setVisible(false);
        RGU.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void PanelBckbtmcerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBckbtmcerrarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PanelBckbtmcerrarMousePressed

    private void PanelBckbtmcerrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBckbtmcerrarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_PanelBckbtmcerrarMouseDragged

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        PanelBckbtmLogin.setBackground(new Color(21,171,146));
        lblLogin.setForeground(Color.white);
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        PanelBckbtmLogin.setBackground(Color.WHITE);
        lblLogin.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseEntered
        PanelBckbtmRegistrar.setBackground(new Color(21,171,146));
        lblRegistro.setForeground(Color.white);
    }//GEN-LAST:event_lblRegistroMouseEntered

    private void lblRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseExited
        PanelBckbtmRegistrar.setBackground(Color.WHITE);
        lblRegistro.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_lblRegistroMouseExited

    private void btmextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmextMouseClicked
            this.setExtendedState(1);
    }//GEN-LAST:event_btmextMouseClicked

    private void btmestcxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmestcxMouseClicked
        EstadoServidor.getInstancia();
    }//GEN-LAST:event_btmestcxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }
    
    /*
    Creacion de una funcion la cual se encarga de escalar la imagenes dentro de los JLabels.
    By: Diego Román
    */
    private void SetImageLabel(JLabel labelname, String root){
    ImageIcon image = new ImageIcon(root);
    Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
    labelname.setIcon(icon);
    this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBckBase;
    private javax.swing.JPanel PanelBckbtmLogin;
    private javax.swing.JPanel PanelBckbtmRegistrar;
    private javax.swing.JPanel PanelBckbtmcerrar;
    private javax.swing.JPanel PanelBckder;
    private javax.swing.JLabel btmclose;
    private javax.swing.JLabel btmestcx;
    private javax.swing.JLabel btmext;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMinicio;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblimgUser;
    private javax.swing.JLabel lblpass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
