/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego EC Roman
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    int xMouse, yMouse;
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelBarraEstado = new javax.swing.JPanel();
        btmcerrar = new javax.swing.JLabel();
        btmMini = new javax.swing.JLabel();
        PanelBckizq = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBckder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBarraEstado.setOpaque(false);
        PanelBarraEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelBarraEstadoMouseDragged(evt);
            }
        });
        PanelBarraEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBarraEstadoMousePressed(evt);
            }
        });

        btmcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N
        btmcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmcerrarMouseClicked(evt);
            }
        });

        btmMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-40.png"))); // NOI18N
        btmMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmMiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBarraEstadoLayout = new javax.swing.GroupLayout(PanelBarraEstado);
        PanelBarraEstado.setLayout(PanelBarraEstadoLayout);
        PanelBarraEstadoLayout.setHorizontalGroup(
            PanelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraEstadoLayout.createSequentialGroup()
                .addGap(0, 864, Short.MAX_VALUE)
                .addComponent(btmMini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmcerrar))
        );
        PanelBarraEstadoLayout.setVerticalGroup(
            PanelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btmMini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelBase.add(PanelBarraEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        PanelBckizq.setBackground(new java.awt.Color(21, 171, 146));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-log-out-50.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBckizqLayout = new javax.swing.GroupLayout(PanelBckizq);
        PanelBckizq.setLayout(PanelBckizqLayout);
        PanelBckizqLayout.setHorizontalGroup(
            PanelBckizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckizqLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        PanelBckizqLayout.setVerticalGroup(
            PanelBckizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckizqLayout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );

        PanelBase.add(PanelBckizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        PanelBckder.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelBckderLayout = new javax.swing.GroupLayout(PanelBckder);
        PanelBckder.setLayout(PanelBckderLayout);
        PanelBckderLayout.setHorizontalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        PanelBckderLayout.setVerticalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        PanelBase.add(PanelBckder, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 710, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btmcerrarMouseClicked

    private void btmMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmMiniMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_btmMiniMouseClicked

    private void PanelBarraEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraEstadoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PanelBarraEstadoMousePressed

    private void PanelBarraEstadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraEstadoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_PanelBarraEstadoMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int sel = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere salir de la sesión actual?", "Log out", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (sel == 0) {
            JOptionPane.showMessageDialog(null, "Sesión cerrada correctamente");
            MenuInicio mi = new MenuInicio();
            this.setVisible(false);
            mi.setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBarraEstado;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelBckder;
    private javax.swing.JPanel PanelBckizq;
    private javax.swing.JLabel btmMini;
    private javax.swing.JLabel btmcerrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
