/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazes;

import java.awt.Color;
import clases.Rusuarios;
import clases.SqlUsuarios;
import javax.swing.JOptionPane;
/**
 *
 * @author Diego EC Roman
 */
public class RegistroUser extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUser
     */
    int xMouse, yMouse;
    public RegistroUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        PanelBarraEstado = new javax.swing.JPanel();
        lblbtmcerrar = new javax.swing.JLabel();
        lblminimizar = new javax.swing.JLabel();
        PanelBckizq = new javax.swing.JPanel();
        lblimgregister = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBckder = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtcorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtpassword = new javax.swing.JPasswordField();
        txtcpassword = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        lblimglogo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblcpassword = new javax.swing.JLabel();
        lblimgruser = new javax.swing.JLabel();
        lblimgrcorreo = new javax.swing.JLabel();
        lblrpassword = new javax.swing.JLabel();
        lblrcpassword = new javax.swing.JLabel();
        PanelBckregistrar = new javax.swing.JPanel();
        lblbtmregistrar = new javax.swing.JLabel();
        PanelBckRcancelar = new javax.swing.JPanel();
        lblbtmrcancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBarraEstado.setOpaque(false);
        PanelBarraEstado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelBarraEstadoMouseDragged(evt);
            }
        });
        PanelBarraEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBarraEstadoMousePressed(evt);
            }
        });

        lblbtmcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerca-40.png"))); // NOI18N
        lblbtmcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbtmcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbtmcerrarMouseClicked(evt);
            }
        });

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menos-40.png"))); // NOI18N
        lblminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBarraEstadoLayout = new javax.swing.GroupLayout(PanelBarraEstado);
        PanelBarraEstado.setLayout(PanelBarraEstadoLayout);
        PanelBarraEstadoLayout.setHorizontalGroup(
            PanelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraEstadoLayout.createSequentialGroup()
                .addGap(0, 864, Short.MAX_VALUE)
                .addComponent(lblminimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbtmcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelBarraEstadoLayout.setVerticalGroup(
            PanelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraEstadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblbtmcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblminimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelBase.add(PanelBarraEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        PanelBckizq.setBackground(new java.awt.Color(21, 171, 146));

        lblimgregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-register-100.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORMULARIO DE REGISTRO");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("V. 1.0");

        javax.swing.GroupLayout PanelBckizqLayout = new javax.swing.GroupLayout(PanelBckizq);
        PanelBckizq.setLayout(PanelBckizqLayout);
        PanelBckizqLayout.setHorizontalGroup(
            PanelBckizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckizqLayout.createSequentialGroup()
                .addGroup(PanelBckizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBckizqLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblimgregister))
                    .addGroup(PanelBckizqLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        PanelBckizqLayout.setVerticalGroup(
            PanelBckizqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckizqLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lblimgregister)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        PanelBase.add(PanelBckizq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        PanelBckder.setBackground(new java.awt.Color(255, 255, 255));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setForeground(new java.awt.Color(190, 193, 198));
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setForeground(new java.awt.Color(190, 193, 198));
        txtcorreo.setText("Correo");
        txtcorreo.setBorder(null);
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setForeground(new java.awt.Color(190, 193, 198));
        txtpassword.setText("******");
        txtpassword.setBorder(null);
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpasswordMousePressed(evt);
            }
        });

        txtcpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtcpassword.setForeground(new java.awt.Color(190, 193, 198));
        txtcpassword.setText("******");
        txtcpassword.setBorder(null);
        txtcpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcpasswordMousePressed(evt);
            }
        });
        txtcpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpasswordActionPerformed(evt);
            }
        });

        lblimglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-accede-redondeado-derecho-100.png"))); // NOI18N

        lblusuario.setForeground(new java.awt.Color(0, 0, 0));
        lblusuario.setText("Nombre de Usuario:");

        lblcorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblcorreo.setText("Correo electronico:");

        lblpassword.setForeground(new java.awt.Color(0, 0, 0));
        lblpassword.setText("Contraseña:");

        lblcpassword.setForeground(new java.awt.Color(0, 0, 0));
        lblcpassword.setText("Confirmar Contraseña:");

        lblimgruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-24.png"))); // NOI18N

        lblimgrcorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-correo-24.png"))); // NOI18N

        lblrpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-desbloquear-24.png"))); // NOI18N

        lblrcpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-desbloquear-24.png"))); // NOI18N

        PanelBckregistrar.setBackground(new java.awt.Color(255, 255, 255));

        lblbtmregistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbtmregistrar.setForeground(new java.awt.Color(21, 171, 146));
        lblbtmregistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbtmregistrar.setText("REGISTRAR");
        lblbtmregistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        lblbtmregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbtmregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbtmregistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbtmregistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbtmregistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckregistrarLayout = new javax.swing.GroupLayout(PanelBckregistrar);
        PanelBckregistrar.setLayout(PanelBckregistrarLayout);
        PanelBckregistrarLayout.setHorizontalGroup(
            PanelBckregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PanelBckregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblbtmregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        PanelBckregistrarLayout.setVerticalGroup(
            PanelBckregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PanelBckregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblbtmregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        PanelBckRcancelar.setBackground(new java.awt.Color(255, 255, 255));

        lblbtmrcancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbtmrcancelar.setForeground(new java.awt.Color(21, 171, 146));
        lblbtmrcancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbtmrcancelar.setText("CANCELAR");
        lblbtmrcancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 171, 146), 2));
        lblbtmrcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbtmrcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbtmrcancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbtmrcancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbtmrcancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBckRcancelarLayout = new javax.swing.GroupLayout(PanelBckRcancelar);
        PanelBckRcancelar.setLayout(PanelBckRcancelarLayout);
        PanelBckRcancelarLayout.setHorizontalGroup(
            PanelBckRcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PanelBckRcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblbtmrcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        PanelBckRcancelarLayout.setVerticalGroup(
            PanelBckRcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(PanelBckRcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblbtmrcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBckderLayout = new javax.swing.GroupLayout(PanelBckder);
        PanelBckder.setLayout(PanelBckderLayout);
        PanelBckderLayout.setHorizontalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckderLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckderLayout.createSequentialGroup()
                        .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimgruser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblimgrcorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblrpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblrcpassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcpassword)
                            .addComponent(lblpassword)
                            .addComponent(lblcorreo)
                            .addComponent(lblusuario)
                            .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4)
                                .addComponent(txtcpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcorreo)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUsuario)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckderLayout.createSequentialGroup()
                        .addComponent(PanelBckregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelBckRcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBckderLayout.createSequentialGroup()
                        .addComponent(lblimglogo)
                        .addGap(152, 152, 152))))
        );
        PanelBckderLayout.setVerticalGroup(
            PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBckderLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblimglogo)
                .addGap(18, 18, 18)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimgruser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblcorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimgrcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblcpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrcpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBckderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBckRcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBckregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        PanelBase.add(PanelBckder, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 410, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbtmcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblbtmcerrarMouseClicked

    private void PanelBarraEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraEstadoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PanelBarraEstadoMousePressed

    private void PanelBarraEstadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraEstadoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_PanelBarraEstadoMouseDragged

    private void txtcpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblbtmregistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmregistrarMouseEntered
        PanelBckregistrar.setBackground(new Color(21,171,146));
        lblbtmregistrar.setForeground(Color.white);
    }//GEN-LAST:event_lblbtmregistrarMouseEntered

    private void lblbtmregistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmregistrarMouseExited
        PanelBckregistrar.setBackground(Color.WHITE);
        lblbtmregistrar.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_lblbtmregistrarMouseExited

    private void lblbtmrcancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmrcancelarMouseEntered
        PanelBckRcancelar.setBackground(new Color(21,171,146));
        lblbtmrcancelar.setForeground(Color.white);
    }//GEN-LAST:event_lblbtmrcancelarMouseEntered

    private void lblbtmrcancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmrcancelarMouseExited
        PanelBckRcancelar.setBackground(Color.WHITE);
        lblbtmrcancelar.setForeground(new Color(21, 171, 146));
    }//GEN-LAST:event_lblbtmrcancelarMouseExited

    private void lblbtmregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmregistrarMouseClicked
        SqlUsuarios modSql = new SqlUsuarios();
        Rusuarios mod = new Rusuarios();

        String pass = String.valueOf(txtpassword.getPassword());
        String cpass = String.valueOf(txtcpassword.getPassword());
        if (txtUsuario.getText().equals("") || pass.equals("") || cpass.equals("") || txtcorreo.getText().equals("") || txtUsuario.getText().equals("Usuario")||txtcorreo.getText().equals("Correo")||pass.equals("******")||cpass.equals("******")) {
            JOptionPane.showMessageDialog(this, "Alguno de los campos esta en blanco");
        } else {
            if (pass.equals(cpass)) {
                mod.setUser(txtUsuario.getText());
                mod.setCorreo(txtcorreo.getText());
                mod.setPassword(pass);
                mod.setId_tipo(1);

                if (modSql.registrar(mod)) {
                    JOptionPane.showMessageDialog(this, "Registro del usuario " + txtUsuario.getText() + " efectuado correctamente");
                    cleanc();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al registar el usuario");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            }
    }                                            
    }//GEN-LAST:event_lblbtmregistrarMouseClicked

    private void lblbtmrcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtmrcancelarMouseClicked
        MenuInicio pni = new MenuInicio();
        pni.setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_lblbtmrcancelarMouseClicked

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (txtUsuario.getText().equals("Usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(txtpassword.getPassword()).isEmpty()) {
            txtpassword.setText("******");
            txtpassword.setForeground(new Color(190, 193, 198));
        }
        if (txtcorreo.getText().equals("")) {
            txtcorreo.setText("Correo");
            txtcorreo.setForeground(new Color(190, 193, 198));
        }
        if (String.valueOf(txtcpassword.getPassword()).isEmpty()) {
            txtcpassword.setText("******");
            txtcpassword.setForeground(new Color(190, 193, 198));
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMousePressed
        if (String.valueOf(txtpassword.getPassword()).equals("******")) {
            txtpassword.setText("");
            txtpassword.setForeground(Color.BLACK);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(new Color(190, 193, 198));
        }
        if (txtcorreo.getText().equals("")) {
            txtcorreo.setText("Correo");
            txtcorreo.setForeground(new Color(190, 193, 198));
        }
        if (String.valueOf(txtcpassword.getPassword()).isEmpty()) {
            txtcpassword.setText("******");
            txtcpassword.setForeground(new Color(190, 193, 198));
        }
    }//GEN-LAST:event_txtpasswordMousePressed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        if (txtcorreo.getText().equals("Correo")) {
            txtcorreo.setText("");
            txtcorreo.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(new Color(190, 193, 198));
        }
        if (String.valueOf(txtpassword.getPassword()).isEmpty()) {
            txtpassword.setText("******");
            txtpassword.setForeground(new Color(190, 193, 198));
        }
        if (String.valueOf(txtcpassword.getPassword()).isEmpty()) {
            txtcpassword.setText("******");
            txtcpassword.setForeground(new Color(190, 193, 198));
        }
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcpasswordMousePressed
        if (String.valueOf(txtcpassword.getPassword()).equals("******")) {
            txtcpassword.setText("");
            txtcpassword.setForeground(Color.BLACK);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(new Color(190, 193, 198));
        }
        if (txtcorreo.getText().equals("")) {
            txtcorreo.setText("Correo");
            txtcorreo.setForeground(new Color(190, 193, 198));
        }
        if (String.valueOf(txtpassword.getPassword()).isEmpty()) {
            txtpassword.setText("******");
            txtpassword.setForeground(new Color(190, 193, 198));
        }
    }//GEN-LAST:event_txtcpasswordMousePressed

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_lblminimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUser().setVisible(true);
            }
        });
    }
    
    private void cleanc() {
        txtUsuario.setText("");
        txtcorreo.setText("");
        txtpassword.setText("");
        txtcpassword.setText("");
        MenuInicio mn = new MenuInicio();
        mn.setVisible(true);
        this.setVisible(false);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBarraEstado;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelBckRcancelar;
    private javax.swing.JPanel PanelBckder;
    private javax.swing.JPanel PanelBckizq;
    private javax.swing.JPanel PanelBckregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblbtmcerrar;
    private javax.swing.JLabel lblbtmrcancelar;
    private javax.swing.JLabel lblbtmregistrar;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblcpassword;
    private javax.swing.JLabel lblimglogo;
    private javax.swing.JLabel lblimgrcorreo;
    private javax.swing.JLabel lblimgregister;
    private javax.swing.JLabel lblimgruser;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblrcpassword;
    private javax.swing.JLabel lblrpassword;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JPasswordField txtcpassword;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
